development:
  adapter: mysql2
  database: SchoolSystem
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: SchoolSystem_test
  username: root
  password:
  host: localhost
